In [47]:
# Swami Shreeji

In [48]:
import pandas as pd

In [49]:
# Series
data = [10, 20, 30, 40]
s = pd.Series(data)
print(f"Series : -> \n\n{s}")

Series : ->

0    10
1    20
2    30
3    40
dtype: int64

In [50]:
# Dataframe
data = {
"Name": ["Amit", "Rahul", "Priya"],
"Marks": [85, 90, 78]
}
df = pd.DataFrame(data)
print(df)

    Name  Marks
0   Amit     85
1  Rahul     90
2  Priya     78

In [51]:
df = pd.read_csv("StudentsPerformance.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,NaN,72,74
1,female,group C,some college,standard,completed,NaN,90,88
2,female,group B,master's degree,standard,none,90.0,95,93
3,male,group A,associate's degree,free/reduced,none,47.0,57,44
4,male,group C,some college,standard,none,76.0,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95
996,male,group C,high school,free/reduced,none,62.0,55,55
997,female,group C,high school,free/reduced,completed,59.0,71,65
998,female,group D,some college,standard,completed,68.0,78,77
999,female,group D,some college,free/reduced,none,77.0,86,86

In [52]:
print(df.head())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none         NaN             72             74
1               completed         NaN             90             88
2                    none        90.0             95             93
3                    none        47.0             57             44
4                    none        76.0             78             75

In [53]:
print(df.tail())

     gender race/ethnicity parental level of education         lunch  \
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
995               completed        88.0             99             95
996                    none        62.0             55             55
997               completed        59.0             71             65
998               completed        68.0             78             77
999                    none        77.0             86             86

In [54]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   998 non-null    float64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 62.6+ KB
None

In [55]:
print(df.describe())

       math score  reading score  writing score
count  998.000000    1000.000000    1000.000000
mean    66.080160      69.169000      68.054000
std     15.176844      14.600192      15.195657
min      0.000000      17.000000      10.000000
25%     57.000000      59.000000      57.750000
50%     66.000000      70.000000      69.000000
75%     77.000000      79.000000      79.000000
max    100.000000     100.000000     100.000000

In [56]:
print(df["gender"])

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [57]:
print(df[["gender", "lunch"]])

     gender         lunch
0    female      standard
1    female      standard
2    female      standard
3      male  free/reduced
4      male      standard
..      ...           ...
995  female      standard
996    male  free/reduced
997  female  free/reduced
998  female      standard
999  female  free/reduced

[1000 rows x 2 columns]

In [58]:
print(df.iloc[0])

gender                                    female
race/ethnicity                           group B
parental level of education    bachelor's degree
lunch                                   standard
test preparation course                     none
math score                                   NaN
reading score                                 72
writing score                                 74
Name: 0, dtype: object

In [59]:
print(df[df["math score"] > 80])

     gender race/ethnicity parental level of education         lunch  \
2    female        group B             master's degree      standard
6    female        group B                some college      standard
16     male        group C                 high school      standard
34     male        group E                some college      standard
35     male        group E          associate's degree      standard
..      ...            ...                         ...           ...
979  female        group C          associate's degree      standard
981    male        group D            some high school      standard
987    male        group E            some high school      standard
990    male        group E                 high school  free/reduced
995  female        group E             master's degree      standard

    test preparation course  math score  reading score  writing score
2                      none        90.0             95             93
6                 completed        88.0             95             92
16                     none        88.0             89             86
34                     none        97.0             87             82
35                completed        81.0             81             79
..                      ...         ...            ...            ...
979                    none        91.0             95             94
981                    none        81.0             78             78
987               completed        81.0             75             76
990               completed        86.0             81             75
995               completed        88.0             99             95

[176 rows x 8 columns]

In [60]:
# Adding New Column
# df["Result"] = "Pass"
# print(df)

In [61]:
# Updating Data
# df.loc[0, "Marks"] = 95

In [62]:
# Deleting Column
# df.drop("Result", axis=1, inplace=True) # axis=1 means Column operation
# inplace=True means changes original DataFrame permanently

In [63]:
df.sort_values("reading score")

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0.0,17,10
327,male,group A,some college,free/reduced,none,28.0,23,19
596,male,group B,high school,free/reduced,none,30.0,24,15
980,female,group B,high school,free/reduced,none,8.0,24,23
76,male,group E,some high school,standard,none,30.0,26,22
...,...,...,...,...,...,...,...,...
106,female,group D,master's degree,standard,none,87.0,100,100
594,female,group C,bachelor's degree,standard,completed,92.0,100,99
962,female,group E,associate's degree,standard,none,100.0,100,100
179,female,group D,some high school,standard,completed,97.0,100,100
458,female,group E,bachelor's degree,standard,none,100.0,100,100

In [64]:
df.sort_values("reading score", ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
546,female,group A,some high school,standard,completed,92.0,100,97
970,female,group D,bachelor's degree,standard,none,89.0,100,100
149,male,group E,associate's degree,free/reduced,completed,100.0,100,93
566,female,group E,bachelor's degree,free/reduced,completed,92.0,100,100
712,female,group D,some college,standard,none,98.0,100,99
...,...,...,...,...,...,...,...,...
76,male,group E,some high school,standard,none,30.0,26,22
980,female,group B,high school,free/reduced,none,8.0,24,23
596,male,group B,high school,free/reduced,none,30.0,24,15
327,male,group A,some college,free/reduced,none,28.0,23,19
59,female,group C,some high school,free/reduced,none,0.0,17,10

In [65]:
high_marks = df[df["reading score"] > 80]
print(high_marks)

     gender race/ethnicity parental level of education         lunch  \
1    female        group C                some college      standard
2    female        group B             master's degree      standard
5    female        group B          associate's degree      standard
6    female        group B                some college      standard
12   female        group B                 high school      standard
..      ...            ...                         ...           ...
989  female        group D                some college  free/reduced
990    male        group E                 high school  free/reduced
991  female        group B            some high school      standard
995  female        group E             master's degree      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
1                 completed         NaN             90             88
2                      none        90.0             95             93
5                      none        71.0             83             78
6                 completed        88.0             95             92
12                     none        65.0             81             73
..                      ...         ...            ...            ...
989               completed        67.0             86             83
990               completed        86.0             81             75
991               completed        65.0             82             78
995               completed        88.0             99             95
999                    none        77.0             86             86

[235 rows x 8 columns]

In [66]:
print(df.isnull())

     gender  race/ethnicity  parental level of education  lunch  \
0     False           False                        False  False
1     False           False                        False  False
2     False           False                        False  False
3     False           False                        False  False
4     False           False                        False  False
..      ...             ...                          ...    ...
995   False           False                        False  False
996   False           False                        False  False
997   False           False                        False  False
998   False           False                        False  False
999   False           False                        False  False

     test preparation course  math score  reading score  writing score
0                      False        True          False          False
1                      False        True          False          False
2                      False       False          False          False
3                      False       False          False          False
4                      False       False          False          False
..                       ...         ...            ...            ...
995                    False       False          False          False
996                    False       False          False          False
997                    False       False          False          False
998                    False       False          False          False
999                    False       False          False          False

[1000 rows x 8 columns]

In [67]:
print(df.isnull().sum())

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     2
reading score                  0
writing score                  0
dtype: int64

In [68]:
df.dropna()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
2,female,group B,master's degree,standard,none,90.0,95,93
3,male,group A,associate's degree,free/reduced,none,47.0,57,44
4,male,group C,some college,standard,none,76.0,78,75
5,female,group B,associate's degree,standard,none,71.0,83,78
6,female,group B,some college,standard,completed,88.0,95,92
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95
996,male,group C,high school,free/reduced,none,62.0,55,55
997,female,group C,high school,free/reduced,completed,59.0,71,65
998,female,group D,some college,standard,completed,68.0,78,77
999,female,group D,some college,free/reduced,none,77.0,86,86

In [69]:
df.fillna(0)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,0.0,72,74
1,female,group C,some college,standard,completed,0.0,90,88
2,female,group B,master's degree,standard,none,90.0,95,93
3,male,group A,associate's degree,free/reduced,none,47.0,57,44
4,male,group C,some college,standard,none,76.0,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88.0,99,95
996,male,group C,high school,free/reduced,none,62.0,55,55
997,female,group C,high school,free/reduced,completed,59.0,71,65
998,female,group D,some college,standard,completed,68.0,78,77
999,female,group D,some college,free/reduced,none,77.0,86,86

In [70]:
data = {"Department": ["IT", "HR", "IT", "HR"],"Salary": [50000, 40000, 60000, 45000]}
df = pd.DataFrame(data)
print(df.groupby("Department")["Salary"].mean())

Department
HR    42500.0
IT    55000.0
Name: Salary, dtype: float64

In [71]:
df1 = pd.DataFrame({"ID": [1,2],"Name": ["Amit","Rahul"]})
df2 = pd.DataFrame({"ID": [1,2],"Marks": [85,90]})
result = pd.merge(df1, df2, on="ID")
print(result)

   ID   Name  Marks
0   1   Amit     85
1   2  Rahul     90

In [72]:
import pandas as pd

new = {
    "Name": ["Amit", "Rahul", "Priya", "Neha"],
    "Marks": [85, 92, 78, 88],
    "City": ["Surat", "Delhi", "Mumbai", "Surat"]
}

df = pd.DataFrame(new)

print(f"Dataset : \n\n{df}\n\n")
print(f"Average Marks : {df['Marks'].mean()}")
print(f"Max Value : {df['Marks'].max()}")
print(f"Min Value : {df['Marks'].min()}\n\n")
print(f"Students Scoring More Than 80 : \n\n{df[df["Marks"] > 80]}\n\n")
print(f"Average Marks City Wise : \n\n{df.groupby("City")["Marks"].mean()}\n\n")

Dataset :

    Name  Marks    City
0   Amit     85   Surat
1  Rahul     92   Delhi
2  Priya     78  Mumbai
3   Neha     88   Surat


Average Marks : 85.75
Max Value : 92
Min Value : 78


Students Scoring More Than 80 :

    Name  Marks   City
0   Amit     85  Surat
1  Rahul     92  Delhi
3   Neha     88  Surat


Average Marks City Wise :

City
Delhi     92.0
Mumbai    78.0
Surat     86.5
Name: Marks, dtype: float64

Thank You - Jay Swaminarayan